nelmio_api_doc:
    documentation:
        info:
            title: Mon API FILM
            description: Documentation de mon API de gestion de films.
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api
            
